# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
#
---
include:
#  - board: zaphod
#  - board: seeeduino_xiao_ble
#    shield: bad_wings_slim
#  - board: seeeduino_xiao_ble
#    shield: dust_left
#  - board: seeeduino_xiao_ble
#    shield: dust_right
#  - board: nice_nano_v2
#    shield: klor_left
#  - board: nice_nano_v2
#    shield: klor_right
#  - board: nice_nano_v2
#    shield: settings_reset
#    shield: microdox_left
#  - board: nice_nano_v2
#    shield: microdox_right

#    shield: settings_reset

  - board: corneish_zen_v1_left # requires calsoylar's fork (see west.yml)
#    shield: settings_reset
#    cmake-args: -DCONFIG_ZMK_DISPLAY=n
  - board: corneish_zen_v1_right
#    shield: settings_reset
#    cmake-args: -DCONFIG_ZMK_DISPLAY=n


#  - board: nice_nano_v2
#    shield: kyria_left
#  - board: nice_nano_v2
#    shield: kyria_right
#  - board: nice_nano_v2
#    shield: rollow
#  - board: nice_nano_v2
#    shield: kyria_v1

#  - board: nice_nano_v2
#    shield: ffkb

#    - board: seeeduino_xiao_ble
#    shield: neuro36

#  - board: seeeduino_xiao_ble
#    shield: midge
