# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
#
---
include:
  - board: zaphod
  - board: seeeduino_xiao_ble
    shield: bad_wings_slim
  - board: seeeduino_xiao_ble
    shield: dust_left
  - board: seeeduino_xiao_ble
    shield: dust_right
  - board: nice_nano_v2
    shield: microdox_left
  - board: nice_nano_v2
    shield: microdox_right

#    shield: settings_reset

# Zen uses calsoylar's fork for display enhancements (see west.yml)
# Building will fail on ZMK main because the modules aren't there.
#  - board: corneish_zen_v1_left
#    shield: settings_reset
#    cmake-args: -DCONFIG_ZMK_DISPLAY=n
#  - board: corneish_zen_v1_right
#    shield: settings_reset
#    cmake-args: -DCONFIG_ZMK_DISPLAY=n


#  - board: nice_nano_v2
#    shield: kyria_left
#  - board: nice_nano_v2
#    shield: kyria_right
#  - board: nice_nano_v2
#    shield: rollow

#  - board: nice_nano_v2
#    shield: ffkb

#    - board: seeeduino_xiao_ble
#    shield: neuro36

#  - board: seeeduino_xiao_ble
#    shield: midge

#  - board: nice_nano_v2
#    shield: klor_left
#  - board: nice_nano_v2
#    shield: klor_right
