# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # - board: nice_nano@2//zmk
  #   shield: hypergolic_left
  # - board: nice_nano@2//zmk
  #   shield: hypergolic_right
  # - board: corneish_zen_right@1//zmk
  # - board: corneish_zen_left@2//zmk
  - board: xiao_ble//zmk
    shield: rommana_left rgbled_adapter
  - board: xiao_ble//zmk
    shield: rommana_right rgbled_adapter
  # - board: xiao_ble//zmk
  #   shield: grumpybird rgbled_adapter
  # - board: xiao_ble//zmk
  #   shield: hummingbird rgbled_adapter
  # - board: xiao_ble//zmk
  #   shield: visorbearer
  # - board: xiao_ble//zmk
  #   shield: adept
