file_format: "1"
id: swweeep
name: Swweeep
type: shield
url: https://github.com/sadekbaroudi/sweep36
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - swweeep_left
  - swweeep_right
