file_format: "1"
id: kyria_rev2
name: Kyria Rev2
type: shield
url: https://splitkb.com/products/kyria-pcb-kit
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - kyria_rev2_left
  - kyria_rev2_right
