file_format: "1"
id: klor
name: KLOR
type: shield
url: https://github.com/GEIGEIGEIST/KLOR
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - klor_left
  - klor_right
